/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EVENT_SET_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EVENT_SET_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EVENT_SET_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        shctiJNI.delete_EVENT_SET_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDwWorkMode(long value) {
    shctiJNI.EVENT_SET_INFO_dwWorkMode_set(swigCPtr, this, value);
  }

  public long getDwWorkMode() {
    return shctiJNI.EVENT_SET_INFO_dwWorkMode_get(swigCPtr, this);
  }

  public void setLpHandlerParam(SWIGTYPE_p_void value) {
    shctiJNI.EVENT_SET_INFO_lpHandlerParam_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getLpHandlerParam() {
    long cPtr = shctiJNI.EVENT_SET_INFO_lpHandlerParam_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDwOutCondition(long value) {
    shctiJNI.EVENT_SET_INFO_dwOutCondition_set(swigCPtr, this, value);
  }

  public long getDwOutCondition() {
    return shctiJNI.EVENT_SET_INFO_dwOutCondition_get(swigCPtr, this);
  }

  public void setDwOutParamVal(long value) {
    shctiJNI.EVENT_SET_INFO_dwOutParamVal_set(swigCPtr, this, value);
  }

  public long getDwOutParamVal() {
    return shctiJNI.EVENT_SET_INFO_dwOutParamVal_get(swigCPtr, this);
  }

  public void setDwUser(long value) {
    shctiJNI.EVENT_SET_INFO_dwUser_set(swigCPtr, this, value);
  }

  public long getDwUser() {
    return shctiJNI.EVENT_SET_INFO_dwUser_get(swigCPtr, this);
  }

  public EVENT_SET_INFO() {
    this(shctiJNI.new_EVENT_SET_INFO(), true);
  }

}
