/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FAX_FILE_SCT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FAX_FILE_SCT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FAX_FILE_SCT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        shctiJNI.delete_FAX_FILE_SCT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzFileName(String value) {
    shctiJNI.FAX_FILE_SCT_szFileName_set(swigCPtr, this, value);
  }

  public String getSzFileName() {
    return shctiJNI.FAX_FILE_SCT_szFileName_get(swigCPtr, this);
  }

  public void setNStartPage(int value) {
    shctiJNI.FAX_FILE_SCT_nStartPage_set(swigCPtr, this, value);
  }

  public int getNStartPage() {
    return shctiJNI.FAX_FILE_SCT_nStartPage_get(swigCPtr, this);
  }

  public void setNEndPage(int value) {
    shctiJNI.FAX_FILE_SCT_nEndPage_set(swigCPtr, this, value);
  }

  public int getNEndPage() {
    return shctiJNI.FAX_FILE_SCT_nEndPage_get(swigCPtr, this);
  }

  public void setNReserve1(int value) {
    shctiJNI.FAX_FILE_SCT_nReserve1_set(swigCPtr, this, value);
  }

  public int getNReserve1() {
    return shctiJNI.FAX_FILE_SCT_nReserve1_get(swigCPtr, this);
  }

  public void setNReserve2(int value) {
    shctiJNI.FAX_FILE_SCT_nReserve2_set(swigCPtr, this, value);
  }

  public int getNReserve2() {
    return shctiJNI.FAX_FILE_SCT_nReserve2_get(swigCPtr, this);
  }

  public FAX_FILE_SCT() {
    this(shctiJNI.new_FAX_FILE_SCT(), true);
  }

}
