/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class shcti implements shctiConstants {
  public static SWIGTYPE_p_int new_intp() {
    long cPtr = shctiJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = shctiJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    shctiJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    shctiJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return shctiJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static int SsmStartCti(String lpSsmCfgFileName, String lpIndexCfgFileName) {
    return shctiJNI.SsmStartCti(lpSsmCfgFileName, lpIndexCfgFileName);
  }

  public static int SsmCloseCti() {
    return shctiJNI.SsmCloseCti();
  }

  public static void SsmGetLastErrMsg(String szErrMsgBuf) {
    shctiJNI.SsmGetLastErrMsg(szErrMsgBuf);
  }

  public static String SsmGetLastErrMsgA() {
    return shctiJNI.SsmGetLastErrMsgA();
  }

  public static int SsmGetLastErrCode() {
    return shctiJNI.SsmGetLastErrCode();
  }

  public static int SsmGetMaxUsableBoard() {
    return shctiJNI.SsmGetMaxUsableBoard();
  }

  public static int SsmGetMaxCfgBoard() {
    return shctiJNI.SsmGetMaxCfgBoard();
  }

  public static int SsmGetRxDtmfBufSize() {
    return shctiJNI.SsmGetRxDtmfBufSize();
  }

  public static int SsmGetAccreditId(int nBId) {
    return shctiJNI.SsmGetAccreditId(nBId);
  }

  public static int SsmGetMaxCh() {
    return shctiJNI.SsmGetMaxCh();
  }

  public static int SsmGetChType(int ch) {
    return shctiJNI.SsmGetChType(ch);
  }

  public static int SsmSetMaxIdxSeg(int wMaxIdxSeg) {
    return shctiJNI.SsmSetMaxIdxSeg(wMaxIdxSeg);
  }

  public static int SsmLoadIndexData(int nSegNo, String pAlias, int nCodec, String pVocFile, int lStartPos, int lLen) {
    return shctiJNI.SsmLoadIndexData(nSegNo, pAlias, nCodec, pVocFile, lStartPos, lLen);
  }

  public static int SsmFreeIndexData(int nSegNo) {
    return shctiJNI.SsmFreeIndexData(nSegNo);
  }

  public static int SsmGetTotalIndexSeg() {
    return shctiJNI.SsmGetTotalIndexSeg();
  }

  public static int SsmPauseCard() {
    return shctiJNI.SsmPauseCard();
  }

  public static int SsmRestartCard() {
    return shctiJNI.SsmRestartCard();
  }

  public static int SsmGetAccreditIdEx(int nBId) {
    return shctiJNI.SsmGetAccreditIdEx(nBId);
  }

  public static int SsmGetBoardModel(int nBId) {
    return shctiJNI.SsmGetBoardModel(nBId);
  }

  public static void SsmSetDV(int bEnable) {
    shctiJNI.SsmSetDV(bEnable);
  }

  public static int SsmGetDV() {
    return shctiJNI.SsmGetDV();
  }

  public static long SsmGetPciSerialNo(int nBId) {
    return shctiJNI.SsmGetPciSerialNo(nBId);
  }

  public static long SsmGetIntCount() {
    return shctiJNI.SsmGetIntCount();
  }

  public static int SsmSetListenMode(int nMode) {
    return shctiJNI.SsmSetListenMode(nMode);
  }

  public static int SsmStartBoard(int nBId) {
    return shctiJNI.SsmStartBoard(nBId);
  }

  public static int SsmStopBoard(int nBId) {
    return shctiJNI.SsmStopBoard(nBId);
  }

  public static int SsmGetChHdInfo(int ch, SWIGTYPE_p_int pnBId, SWIGTYPE_p_int pnBCh) {
    return shctiJNI.SsmGetChHdInfo(ch, SWIGTYPE_p_int.getCPtr(pnBId), SWIGTYPE_p_int.getCPtr(pnBCh));
  }

  public static int SsmGetAppChId(SWIGTYPE_p_int AppchId, int BrdId, int BrdChId) {
    return shctiJNI.SsmGetAppChId(SWIGTYPE_p_int.getCPtr(AppchId), BrdId, BrdChId);
  }

  public static int SsmSetChState(int ch, int nState) {
    return shctiJNI.SsmSetChState(ch, nState);
  }

  public static int SsmSetPlayVolume(int ch, int nVolume) {
    return shctiJNI.SsmSetPlayVolume(ch, nVolume);
  }

  public static int SsmSetDtmfStopPlay(int ch, int bDspf) {
    return shctiJNI.SsmSetDtmfStopPlay(ch, bDspf);
  }

  public static int SsmGetDtmfStopPlayFlag(int ch) {
    return shctiJNI.SsmGetDtmfStopPlayFlag(ch);
  }

  public static int SsmSetBargeinStopPlay(int ch, int bBispf) {
    return shctiJNI.SsmSetBargeinStopPlay(ch, bBispf);
  }

  public static int SsmGetBargeinStopPlayFlag(int ch) {
    return shctiJNI.SsmGetBargeinStopPlayFlag(ch);
  }

  public static int SsmPlayFile(int ch, String pszFileName, int nFormat, long dwStartPos, long dwLen) {
    return shctiJNI.SsmPlayFile(ch, pszFileName, nFormat, dwStartPos, dwLen);
  }

  public static int SsmStopPlay(int ch) {
    return shctiJNI.SsmStopPlay(ch);
  }

  public static int SsmStopPlayFile(int ch) {
    return shctiJNI.SsmStopPlayFile(ch);
  }

  public static int SsmPausePlay(int ch) {
    return shctiJNI.SsmPausePlay(ch);
  }

  public static int SsmRestartPlay(int ch) {
    return shctiJNI.SsmRestartPlay(ch);
  }

  public static int SsmFastFwdPlay(int ch) {
    return shctiJNI.SsmFastFwdPlay(ch);
  }

  public static int SsmFastBwdPlay(int ch) {
    return shctiJNI.SsmFastBwdPlay(ch);
  }

  public static int SsmSetPlayTime(int ch, long dwTime) {
    return shctiJNI.SsmSetPlayTime(ch, dwTime);
  }

  public static int SsmGetPlayedTimeEx(int ch) {
    return shctiJNI.SsmGetPlayedTimeEx(ch);
  }

  public static int SsmGetPlayingFileInfo(int ch, SWIGTYPE_p_int pnFormat, SWIGTYPE_p_long pnTotalTime) {
    return shctiJNI.SsmGetPlayingFileInfo(ch, SWIGTYPE_p_int.getCPtr(pnFormat), SWIGTYPE_p_long.getCPtr(pnTotalTime));
  }

  public static int SsmSetPlayPrct(int ch, long dwPercentage) {
    return shctiJNI.SsmSetPlayPrct(ch, dwPercentage);
  }

  public static int SsmGetPlayedTime(int ch) {
    return shctiJNI.SsmGetPlayedTime(ch);
  }

  public static int SsmGetPlayedPercentage(int ch) {
    return shctiJNI.SsmGetPlayedPercentage(ch);
  }

  public static int SsmGetDataBytesToPlay(int ch) {
    return shctiJNI.SsmGetDataBytesToPlay(ch);
  }

  public static int SsmCheckPlay(int ch) {
    return shctiJNI.SsmCheckPlay(ch);
  }

  public static int SsmGetPlayType(int ch) {
    return shctiJNI.SsmGetPlayType(ch);
  }

  public static int SsmPlayIndexString(int ch, String pszIdxStr) {
    return shctiJNI.SsmPlayIndexString(ch, pszIdxStr);
  }

  public static int SsmPlayIndexList(int ch, int wIdxListLen, SWIGTYPE_p_unsigned_short pwIdxList) {
    return shctiJNI.SsmPlayIndexList(ch, wIdxListLen, SWIGTYPE_p_unsigned_short.getCPtr(pwIdxList));
  }

  public static int SsmStopPlayIndex(int ch) {
    return shctiJNI.SsmStopPlayIndex(ch);
  }

  public static int SsmClearFileList(int ch) {
    return shctiJNI.SsmClearFileList(ch);
  }

  public static int SsmAddToFileList(int ch, String pszFileName, int nFormat, long dwStartPos, long dwLen) {
    return shctiJNI.SsmAddToFileList(ch, pszFileName, nFormat, dwStartPos, dwLen);
  }

  public static int SsmPlayFileList(int ch) {
    return shctiJNI.SsmPlayFileList(ch);
  }

  public static int SsmStopPlayFileList(int ch) {
    return shctiJNI.SsmStopPlayFileList(ch);
  }

  public static int SsmPlayMem(int ch, int nFormat, SWIGTYPE_p_unsigned_char pBuf, long dwBufSize, long dwStartOffset, long dwStopOffset) {
    return shctiJNI.SsmPlayMem(ch, nFormat, SWIGTYPE_p_unsigned_char.getCPtr(pBuf), dwBufSize, dwStartOffset, dwStopOffset);
  }

  public static int SsmGetPlayOffset(int ch, SWIGTYPE_p_unsigned_long pdwPlayOffset) {
    return shctiJNI.SsmGetPlayOffset(ch, SWIGTYPE_p_unsigned_long.getCPtr(pdwPlayOffset));
  }

  public static int SsmSetStopPlayOffset(int ch, long dwStopPlayOffset) {
    return shctiJNI.SsmSetStopPlayOffset(ch, dwStopPlayOffset);
  }

  public static int SsmStopPlayMem(int ch) {
    return shctiJNI.SsmStopPlayMem(ch);
  }

  public static int SsmClearPlayMemList() {
    return shctiJNI.SsmClearPlayMemList();
  }

  public static int SsmAddToPlayMemList(SWIGTYPE_p_unsigned_char pBuf, long dwDataLen, int nFormat) {
    return shctiJNI.SsmAddToPlayMemList(SWIGTYPE_p_unsigned_char.getCPtr(pBuf), dwDataLen, nFormat);
  }

  public static int SsmPlayMemList(int ch, SWIGTYPE_p_unsigned_short pMemList, int wMemListLen) {
    return shctiJNI.SsmPlayMemList(ch, SWIGTYPE_p_unsigned_short.getCPtr(pMemList), wMemListLen);
  }

  public static int SsmStopPlayMemList(int ch) {
    return shctiJNI.SsmStopPlayMemList(ch);
  }

  public static int SsmSetDTMFStopPlayCharSet(int ch, String lpstrDtmfCharSet) {
    return shctiJNI.SsmSetDTMFStopPlayCharSet(ch, lpstrDtmfCharSet);
  }

  public static int SsmGetDTMFStopPlayCharSet(int ch, String lpstrDtmfCharSet) {
    return shctiJNI.SsmGetDTMFStopPlayCharSet(ch, lpstrDtmfCharSet);
  }

  public static int SsmSetHangupStopPlayFlag(int ch, int bHangupStopRecFlag) {
    return shctiJNI.SsmSetHangupStopPlayFlag(ch, bHangupStopRecFlag);
  }

  public static int SsmPlayMemBlock(int ch, int nFormat, SWIGTYPE_p_unsigned_char pBuf, long dwBufSize, SWIGTYPE_p_PLAYMEMBLOCKHANDLER OnPlayMemBlockDone, SWIGTYPE_p_void pV) {
    return shctiJNI.SsmPlayMemBlock(ch, nFormat, SWIGTYPE_p_unsigned_char.getCPtr(pBuf), dwBufSize, SWIGTYPE_p_PLAYMEMBLOCKHANDLER.getCPtr(OnPlayMemBlockDone), SWIGTYPE_p_void.getCPtr(pV));
  }

  public static int SsmStopPlayMemBlock(int ch) {
    return shctiJNI.SsmStopPlayMemBlock(ch);
  }

  public static int SsmGetDataBytesPlayed(int ch) {
    return shctiJNI.SsmGetDataBytesPlayed(ch);
  }

  public static int SsmSetRecVolume(int ch, int nVolume) {
    return shctiJNI.SsmSetRecVolume(ch, nVolume);
  }

  public static int SsmGetRecType(int ch) {
    return shctiJNI.SsmGetRecType(ch);
  }

  public static int SsmRecToFile(int ch, String pszFileName, int nFormat, long dwStartPos, long dwBytes, long dwTime, int nMask) {
    return shctiJNI.SsmRecToFile(ch, pszFileName, nFormat, dwStartPos, dwBytes, dwTime, nMask);
  }

  public static int SsmRecToFileA(int ch, String pszFileName, int nFormat, long dwStartPos, long dwBytes, long dwTime, int nMask, SWIGTYPE_p_LPRECTOMEM pfnRecToMem) {
    return shctiJNI.SsmRecToFileA(ch, pszFileName, nFormat, dwStartPos, dwBytes, dwTime, nMask, SWIGTYPE_p_LPRECTOMEM.getCPtr(pfnRecToMem));
  }

  public static int SsmRecToFileEx(int ch, String pszFileName, int nFormat, long dwStartPos, long dwBytes, long dwTime, int nMask, int bSaveToFileOnBargin, long dwRollbackTime) {
    return shctiJNI.SsmRecToFileEx(ch, pszFileName, nFormat, dwStartPos, dwBytes, dwTime, nMask, bSaveToFileOnBargin, dwRollbackTime);
  }

  public static int SsmPauseRecToFile(int ch) {
    return shctiJNI.SsmPauseRecToFile(ch);
  }

  public static int SsmRestartRecToFile(int ch) {
    return shctiJNI.SsmRestartRecToFile(ch);
  }

  public static int SsmGetRecTime(int ch) {
    return shctiJNI.SsmGetRecTime(ch);
  }

  public static int SsmGetDataBytesToRecord(int ch) {
    return shctiJNI.SsmGetDataBytesToRecord(ch);
  }

  public static int SsmStopRecToFile(int ch) {
    return shctiJNI.SsmStopRecToFile(ch);
  }

  public static int SsmChkRecToFile(int ch) {
    return shctiJNI.SsmChkRecToFile(ch);
  }

  public static int SsmRecToMem(int ch, int nFormat, SWIGTYPE_p_unsigned_char pBuf, long dwBufSize, long dwStartOffset) {
    return shctiJNI.SsmRecToMem(ch, nFormat, SWIGTYPE_p_unsigned_char.getCPtr(pBuf), dwBufSize, dwStartOffset);
  }

  public static int SsmStopRecToMem(int ch) {
    return shctiJNI.SsmStopRecToMem(ch);
  }

  public static int SsmGetRecOffset(int ch) {
    return shctiJNI.SsmGetRecOffset(ch);
  }

  public static int SsmGetRecAGCSwitch(int ch) {
    return shctiJNI.SsmGetRecAGCSwitch(ch);
  }

  public static int SsmSetRecAGC(int ch, int bEnable) {
    return shctiJNI.SsmSetRecAGC(ch, bEnable);
  }

  public static int SsmQueryOpRecMixer(int ch) {
    return shctiJNI.SsmQueryOpRecMixer(ch);
  }

  public static int SsmSetRecMixer(int ch, int bEnRecMixer, int nMixerVolume) {
    return shctiJNI.SsmSetRecMixer(ch, bEnRecMixer, nMixerVolume);
  }

  public static int SsmGetRecMixerState(int ch, SWIGTYPE_p_int pnEnRecMixer, SWIGTYPE_p_int pnMixerVolume) {
    return shctiJNI.SsmGetRecMixerState(ch, SWIGTYPE_p_int.getCPtr(pnEnRecMixer), SWIGTYPE_p_int.getCPtr(pnMixerVolume));
  }

  public static int SsmSetPrerecord(int ch, int bEnable, int nMode, int wInsertTime, int nFormat) {
    return shctiJNI.SsmSetPrerecord(ch, bEnable, nMode, wInsertTime, nFormat);
  }

  public static int SsmSetTruncateTail(int ch, long dwTime) {
    return shctiJNI.SsmSetTruncateTail(ch, dwTime);
  }

  public static int SsmGetTruncateTailTime(int ch) {
    return shctiJNI.SsmGetTruncateTailTime(ch);
  }

  public static int SsmGetPrerecordState(int ch, SWIGTYPE_p_int pnMode, SWIGTYPE_p_unsigned_short pwInsertTime, SWIGTYPE_p_int pnFormat) {
    return shctiJNI.SsmGetPrerecordState(ch, SWIGTYPE_p_int.getCPtr(pnMode), SWIGTYPE_p_unsigned_short.getCPtr(pwInsertTime), SWIGTYPE_p_int.getCPtr(pnFormat));
  }

  public static int SsmSetDTMFStopRecCharSet(int ch, String lpstrDtmfCharSet) {
    return shctiJNI.SsmSetDTMFStopRecCharSet(ch, lpstrDtmfCharSet);
  }

  public static int SsmGetDTMFStopRecCharSet(int ch, String lpstrDtmfCharSet) {
    return shctiJNI.SsmGetDTMFStopRecCharSet(ch, lpstrDtmfCharSet);
  }

  public static int SsmSetHangupStopRecFlag(int ch, int bHangupStopRecFlag) {
    return shctiJNI.SsmSetHangupStopRecFlag(ch, bHangupStopRecFlag);
  }

  public static int SsmCheckRecord(int ch) {
    return shctiJNI.SsmCheckRecord(ch);
  }

  public static int SsmRecordMemBlock(int ch, int nFormat, SWIGTYPE_p_unsigned_char pBuf, long dwBufSize, SWIGTYPE_p_RECORDMEMBLOCKHANDLER OnRecMemBlockDone, SWIGTYPE_p_void pV) {
    return shctiJNI.SsmRecordMemBlock(ch, nFormat, SWIGTYPE_p_unsigned_char.getCPtr(pBuf), dwBufSize, SWIGTYPE_p_RECORDMEMBLOCKHANDLER.getCPtr(OnRecMemBlockDone), SWIGTYPE_p_void.getCPtr(pV));
  }

  public static int SsmStopRecordMemBlock(int ch) {
    return shctiJNI.SsmStopRecordMemBlock(ch);
  }

  public static int SsmSetNoModuleChBusRec(int ch, int nRec) {
    return shctiJNI.SsmSetNoModuleChBusRec(ch, nRec);
  }

  public static int SsmEnableRxDtmf(int ch, int bRun) {
    return shctiJNI.SsmEnableRxDtmf(ch, bRun);
  }

  public static int SsmClearRxDtmfBuf(int ch) {
    return shctiJNI.SsmClearRxDtmfBuf(ch);
  }

  public static int SsmGetDtmfStr(int ch, String pszDtmf) {
    return shctiJNI.SsmGetDtmfStr(ch, pszDtmf);
  }

  public static String SsmGetDtmfStrA(int ch) {
    return shctiJNI.SsmGetDtmfStrA(ch);
  }

  public static int SsmGetRxDtmfLen(int ch) {
    return shctiJNI.SsmGetRxDtmfLen(ch);
  }

  public static int SsmGet1stDtmf(int ch, String pcDtmf) {
    return shctiJNI.SsmGet1stDtmf(ch, pcDtmf);
  }

  public static int SsmGet1stDtmfClr(int ch, String pcDtmf) {
    return shctiJNI.SsmGet1stDtmfClr(ch, pcDtmf);
  }

  public static int SsmGetLastDtmf(int ch, String pcDtmf) {
    return shctiJNI.SsmGetLastDtmf(ch, pcDtmf);
  }

  public static int SsmSetWaitDtmf(int ch, int wTimeOut, int wMaxLen, char cEndChar, int bWithEndChar) {
    return shctiJNI.SsmSetWaitDtmf(ch, wTimeOut, wMaxLen, cEndChar, bWithEndChar);
  }

  public static int SsmChkWaitDtmf(int ch, String pszDtmf) {
    return shctiJNI.SsmChkWaitDtmf(ch, pszDtmf);
  }

  public static int SsmCancelWaitDtmf(int ch) {
    return shctiJNI.SsmCancelWaitDtmf(ch);
  }

  public static int SsmSetWaitDtmfEx(int ch, int wTimeOut, int wMaxLen, char cEndChar, int bWithEndChar) {
    return shctiJNI.SsmSetWaitDtmfEx(ch, wTimeOut, wMaxLen, cEndChar, bWithEndChar);
  }

  public static int SsmSetRxDtmfHandler(int ch, SWIGTYPE_p_RXDTMFHANDLER OnRcvDtmf, SWIGTYPE_p_void pV) {
    return shctiJNI.SsmSetRxDtmfHandler(ch, SWIGTYPE_p_RXDTMFHANDLER.getCPtr(OnRcvDtmf), SWIGTYPE_p_void.getCPtr(pV));
  }

  public static int SsmSetWaitDtmfExA(int ch, int wTimeOut, int wMaxLen, String szEndChar, int bWithEndChar) {
    return shctiJNI.SsmSetWaitDtmfExA(ch, wTimeOut, wMaxLen, szEndChar, bWithEndChar);
  }

  public static int SsmQueryTxDtmf(int ch, String pszDtmf) {
    return shctiJNI.SsmQueryTxDtmf(ch, pszDtmf);
  }

  public static int SsmQueryTxFlash(int ch, String pszDtmf) {
    return shctiJNI.SsmQueryTxFlash(ch, pszDtmf);
  }

  public static int SsmSetTxDtmfPara(int ch, int wOnTime, int wOffTime) {
    return shctiJNI.SsmSetTxDtmfPara(ch, wOnTime, wOffTime);
  }

  public static int SsmGetTxDtmfPara(int ch, SWIGTYPE_p_unsigned_short pwOnTime, SWIGTYPE_p_unsigned_short pwOffTime) {
    return shctiJNI.SsmGetTxDtmfPara(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwOnTime), SWIGTYPE_p_unsigned_short.getCPtr(pwOffTime));
  }

  public static int SsmTxDtmf(int ch, String pszDtmf) {
    return shctiJNI.SsmTxDtmf(ch, pszDtmf);
  }

  public static int SsmStopTxDtmf(int ch) {
    return shctiJNI.SsmStopTxDtmf(ch);
  }

  public static int SsmChkTxDtmf(int ch) {
    return shctiJNI.SsmChkTxDtmf(ch);
  }

  public static int SsmTxFlash(int ch, int time) {
    return shctiJNI.SsmTxFlash(ch, time);
  }

  public static int SsmChkTxFlash(int ch) {
    return shctiJNI.SsmChkTxFlash(ch);
  }

  public static int SsmSetTxFlashCharTime(int ch, int time) {
    return shctiJNI.SsmSetTxFlashCharTime(ch, time);
  }

  public static int SsmGetTxFlashCharTime(int ch) {
    return shctiJNI.SsmGetTxFlashCharTime(ch);
  }

  public static int SsmSetLocalFlashTime(int nFlashTime) {
    return shctiJNI.SsmSetLocalFlashTime(nFlashTime);
  }

  public static int SsmSetASDT(int ch, int bEnAutoSendDialTone) {
    return shctiJNI.SsmSetASDT(ch, bEnAutoSendDialTone);
  }

  public static int SsmGetASDT(int ch) {
    return shctiJNI.SsmGetASDT(ch);
  }

  public static int SsmSetASTOD(int ch, int bEnAutoSendDialTone) {
    return shctiJNI.SsmSetASTOD(ch, bEnAutoSendDialTone);
  }

  public static int SsmGetASTOD(int ch) {
    return shctiJNI.SsmGetASTOD(ch);
  }

  public static int SsmGetFlashCount(int ch) {
    return shctiJNI.SsmGetFlashCount(ch);
  }

  public static int SsmClearFlashCount(int ch) {
    return shctiJNI.SsmClearFlashCount(ch);
  }

  public static int SsmGetHookState(int ch) {
    return shctiJNI.SsmGetHookState(ch);
  }

  public static int SsmStartRing(int ch) {
    return shctiJNI.SsmStartRing(ch);
  }

  public static int SsmStopRing(int ch) {
    return shctiJNI.SsmStopRing(ch);
  }

  public static int SsmStartRingWithFskCID(int ch, String pBuf, long dwMaxBit, long dw1stRingOffDelay) {
    return shctiJNI.SsmStartRingWithFskCID(ch, pBuf, dwMaxBit, dw1stRingOffDelay);
  }

  public static int SsmStartRingWithCIDStr(int ch, String pBuf, long dwLen, long dw1stRingOffDelay) {
    return shctiJNI.SsmStartRingWithCIDStr(ch, pBuf, dwLen, dw1stRingOffDelay);
  }

  public static int SsmQueryOpSendTone(int ch) {
    return shctiJNI.SsmQueryOpSendTone(ch);
  }

  public static int SsmSendTone(int ch, int nToneType) {
    return shctiJNI.SsmSendTone(ch, nToneType);
  }

  public static int SsmSendToneEx(int ch, long dwOnTime, long dwOffTime) {
    return shctiJNI.SsmSendToneEx(ch, dwOnTime, dwOffTime);
  }

  public static int SsmStopSendTone(int ch) {
    return shctiJNI.SsmStopSendTone(ch);
  }

  public static int SsmSetTxTonePara(int ch, int nFreq1, int nVolume1, int nFreq2, int nVolume2) {
    return shctiJNI.SsmSetTxTonePara(ch, nFreq1, nVolume1, nFreq2, nVolume2);
  }

  public static int SsmGetTxTonePara(int ch, SWIGTYPE_p_int pnFreq1, SWIGTYPE_p_int pnVolume1, SWIGTYPE_p_int pnFreq2, SWIGTYPE_p_int pnVolume2) {
    return shctiJNI.SsmGetTxTonePara(ch, SWIGTYPE_p_int.getCPtr(pnFreq1), SWIGTYPE_p_int.getCPtr(pnVolume1), SWIGTYPE_p_int.getCPtr(pnFreq2), SWIGTYPE_p_int.getCPtr(pnVolume2));
  }

  public static int SsmQueryOpToneAnalyze(int ch) {
    return shctiJNI.SsmQueryOpToneAnalyze(ch);
  }

  public static int SsmClearToneAnalyzeResult(int ch) {
    return shctiJNI.SsmClearToneAnalyzeResult(ch);
  }

  public static int SsmStartToneAnalyze(int ch) {
    return shctiJNI.SsmStartToneAnalyze(ch);
  }

  public static int SsmCloseToneAnalyze(int ch) {
    return shctiJNI.SsmCloseToneAnalyze(ch);
  }

  public static int SsmGetOverallEnergy(int ch) {
    return shctiJNI.SsmGetOverallEnergy(ch);
  }

  public static int SsmGetVocFxFlag(int ch, int nSelFx, int bClear) {
    return shctiJNI.SsmGetVocFxFlag(ch, nSelFx, bClear);
  }

  public static int SsmGetToneAnalyzeResult(int ch) {
    return shctiJNI.SsmGetToneAnalyzeResult(ch);
  }

  public static int SsmGetBusyToneLen(int ch) {
    return shctiJNI.SsmGetBusyToneLen(ch);
  }

  public static int SsmGetBusyToneCount(int ch) {
    return shctiJNI.SsmGetBusyToneCount(ch);
  }

  public static int SsmGetRingEchoToneTime(int ch) {
    return shctiJNI.SsmGetRingEchoToneTime(ch);
  }

  public static int SsmGetBusyToneEx(int ch) {
    return shctiJNI.SsmGetBusyToneEx(ch);
  }

  public static int SsmSetTonePara(int ch, int wToneFreq1, int wToneBW1, int wToneFreq2, int wToneBW2, long dwIsToneRatio) {
    return shctiJNI.SsmSetTonePara(ch, wToneFreq1, wToneBW1, wToneFreq2, wToneBW2, dwIsToneRatio);
  }

  public static int SsmSetIsDialToneDtrTime(int ch, int wIsDialToneDtrTime) {
    return shctiJNI.SsmSetIsDialToneDtrTime(ch, wIsDialToneDtrTime);
  }

  public static int SsmSetBusyTonePeriod(int ch, int wBusyTonePeriod) {
    return shctiJNI.SsmSetBusyTonePeriod(ch, wBusyTonePeriod);
  }

  public static int SsmSetIsBusyToneDtrCnt(int ch, int wIsBusyToneDtrCnt) {
    return shctiJNI.SsmSetIsBusyToneDtrCnt(ch, wIsBusyToneDtrCnt);
  }

  public static int SsmSetRingEchoTonePara(int ch, int wRingEchoOnTime, int wRingEchoOffTime) {
    return shctiJNI.SsmSetRingEchoTonePara(ch, wRingEchoOnTime, wRingEchoOffTime);
  }

  public static int SsmSetVoiceFxPara(int ch, int wSelFx, int wFx, int wFxBW, long dwIsVocFxRatio, int wIsVocFxDtrTime) {
    return shctiJNI.SsmSetVoiceFxPara(ch, wSelFx, wFx, wFxBW, dwIsVocFxRatio, wIsVocFxDtrTime);
  }

  public static int SsmSetVoiceOnDetermineTime(int ch, int wIsVocDtrTime) {
    return shctiJNI.SsmSetVoiceOnDetermineTime(ch, wIsVocDtrTime);
  }

  public static int SsmSetMinVocDtrEnergy(int ch, long dwMinVocDtrEnergy) {
    return shctiJNI.SsmSetMinVocDtrEnergy(ch, dwMinVocDtrEnergy);
  }

  public static int SsmGetTonePara(int ch, SWIGTYPE_p_unsigned_short pwToneFreq1, SWIGTYPE_p_unsigned_short pwToneBW1, SWIGTYPE_p_unsigned_short pwToneFreq2, SWIGTYPE_p_unsigned_short pwToneBW2, SWIGTYPE_p_unsigned_long pdwIsToneRatio) {
    return shctiJNI.SsmGetTonePara(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwToneFreq1), SWIGTYPE_p_unsigned_short.getCPtr(pwToneBW1), SWIGTYPE_p_unsigned_short.getCPtr(pwToneFreq2), SWIGTYPE_p_unsigned_short.getCPtr(pwToneBW2), SWIGTYPE_p_unsigned_long.getCPtr(pdwIsToneRatio));
  }

  public static int SsmGetIsDialToneDtrTime(int ch, SWIGTYPE_p_unsigned_short pwIsDialToneDtrTime) {
    return shctiJNI.SsmGetIsDialToneDtrTime(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwIsDialToneDtrTime));
  }

  public static int SsmGetBusyTonePeriod(int ch, SWIGTYPE_p_unsigned_short pwBusyTonePeriod) {
    return shctiJNI.SsmGetBusyTonePeriod(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwBusyTonePeriod));
  }

  public static int SsmGetIsBusyToneDtrCnt(int ch, SWIGTYPE_p_unsigned_short pwIsBusyToneDtrCnt) {
    return shctiJNI.SsmGetIsBusyToneDtrCnt(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwIsBusyToneDtrCnt));
  }

  public static int SsmGetRingEchoTonePara(int ch, SWIGTYPE_p_unsigned_short pwRingEchoOnTime, SWIGTYPE_p_unsigned_short pwRingEchoOffTime) {
    return shctiJNI.SsmGetRingEchoTonePara(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwRingEchoOnTime), SWIGTYPE_p_unsigned_short.getCPtr(pwRingEchoOffTime));
  }

  public static int SsmGetIsNoVocDtrmTime(int ch, SWIGTYPE_p_unsigned_short pwIsNoVocDtrmTime) {
    return shctiJNI.SsmGetIsNoVocDtrmTime(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwIsNoVocDtrmTime));
  }

  public static int SsmGetVoiceFxPara(int ch, int wSelFx, SWIGTYPE_p_unsigned_short pwFx, SWIGTYPE_p_unsigned_short pwFxBW, SWIGTYPE_p_unsigned_long pdwIsVocFxRatio, SWIGTYPE_p_unsigned_short pwIsVocFxDtrTime) {
    return shctiJNI.SsmGetVoiceFxPara(ch, wSelFx, SWIGTYPE_p_unsigned_short.getCPtr(pwFx), SWIGTYPE_p_unsigned_short.getCPtr(pwFxBW), SWIGTYPE_p_unsigned_long.getCPtr(pdwIsVocFxRatio), SWIGTYPE_p_unsigned_short.getCPtr(pwIsVocFxDtrTime));
  }

  public static int SsmGetVoiceOnDetermineTime(int ch, SWIGTYPE_p_unsigned_short pwIsVocDtrTime) {
    return shctiJNI.SsmGetVoiceOnDetermineTime(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwIsVocDtrTime));
  }

  public static int SsmGetMinVocDtrEnergy(int ch, SWIGTYPE_p_unsigned_long pdwMinVocDtrEnergy) {
    return shctiJNI.SsmGetMinVocDtrEnergy(ch, SWIGTYPE_p_unsigned_long.getCPtr(pdwMinVocDtrEnergy));
  }

  public static int SsmQueryOpPeakFrqDetect(int ch) {
    return shctiJNI.SsmQueryOpPeakFrqDetect(ch);
  }

  public static int SsmSetPeakFrqDetectBW(int ch, int nPeakBW) {
    return shctiJNI.SsmSetPeakFrqDetectBW(ch, nPeakBW);
  }

  public static int SsmGetPeakFrqDetectBW(int ch) {
    return shctiJNI.SsmGetPeakFrqDetectBW(ch);
  }

  public static int SsmGetPeakFrqEnergy(int ch) {
    return shctiJNI.SsmGetPeakFrqEnergy(ch);
  }

  public static int SsmGetPeakFrq(int ch) {
    return shctiJNI.SsmGetPeakFrq(ch);
  }

  public static int SsmStart2ndToneAnalyzer(int ch, int bEn) {
    return shctiJNI.SsmStart2ndToneAnalyzer(ch, bEn);
  }

  public static int SsmGet2ndToneAnalyzerState(int ch) {
    return shctiJNI.SsmGet2ndToneAnalyzerState(ch);
  }

  public static int SsmSet2ndTonePara(int ch, int wToneFreq1, int wToneBW1, int wToneFreq2, int wToneBW2, long dwIsToneRatio) {
    return shctiJNI.SsmSet2ndTonePara(ch, wToneFreq1, wToneBW1, wToneFreq2, wToneBW2, dwIsToneRatio);
  }

  public static int SsmGet2ndTonePara(int ch, SWIGTYPE_p_unsigned_short pwToneFreq1, SWIGTYPE_p_unsigned_short pwToneBW1, SWIGTYPE_p_unsigned_short pwToneFreq2, SWIGTYPE_p_unsigned_short pwToneBW2, SWIGTYPE_p_unsigned_long pdwIsToneRatio) {
    return shctiJNI.SsmGet2ndTonePara(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwToneFreq1), SWIGTYPE_p_unsigned_short.getCPtr(pwToneBW1), SWIGTYPE_p_unsigned_short.getCPtr(pwToneFreq2), SWIGTYPE_p_unsigned_short.getCPtr(pwToneBW2), SWIGTYPE_p_unsigned_long.getCPtr(pdwIsToneRatio));
  }

  public static int SsmGet2ndToneAnalyzeResult(int ch) {
    return shctiJNI.SsmGet2ndToneAnalyzeResult(ch);
  }

  public static int SsmClear2ndToneAnalyzeResult(int ch) {
    return shctiJNI.SsmClear2ndToneAnalyzeResult(ch);
  }

  public static int SsmGet2ndBusyToneLen(int ch) {
    return shctiJNI.SsmGet2ndBusyToneLen(ch);
  }

  public static int SsmGet2ndBusyToneCount(int ch) {
    return shctiJNI.SsmGet2ndBusyToneCount(ch);
  }

  public static int SsmSet2ndBusyTonePeriod(int ch, int wBusyTonePeriod) {
    return shctiJNI.SsmSet2ndBusyTonePeriod(ch, wBusyTonePeriod);
  }

  public static int SsmGet2ndBusyTonePeriod(int ch, SWIGTYPE_p_unsigned_short pwBusyTonePeriod) {
    return shctiJNI.SsmGet2ndBusyTonePeriod(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwBusyTonePeriod));
  }

  public static int SsmSet2ndIsBusyToneDtrCnt(int ch, int wIsBusyToneDtrCnt) {
    return shctiJNI.SsmSet2ndIsBusyToneDtrCnt(ch, wIsBusyToneDtrCnt);
  }

  public static int SsmGet2ndIsBusyToneDtrCnt(int ch, SWIGTYPE_p_unsigned_short pwIsBusyToneDtrCnt) {
    return shctiJNI.SsmGet2ndIsBusyToneDtrCnt(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwIsBusyToneDtrCnt));
  }

  public static int SsmSet2ndIsDialToneDtrTime(int ch, int wIsDialToneDtrTime) {
    return shctiJNI.SsmSet2ndIsDialToneDtrTime(ch, wIsDialToneDtrTime);
  }

  public static int SsmGet2ndIsDialToneDtrTime(int ch, SWIGTYPE_p_unsigned_short pwIsDialToneDtrTime) {
    return shctiJNI.SsmGet2ndIsDialToneDtrTime(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwIsDialToneDtrTime));
  }

  public static int SsmSet2ndRingEchoTonePara(int ch, int wRingEchoOnTime, int wRingEchoOffTime) {
    return shctiJNI.SsmSet2ndRingEchoTonePara(ch, wRingEchoOnTime, wRingEchoOffTime);
  }

  public static int SsmGet2ndRingEchoTonePara(int ch, SWIGTYPE_p_unsigned_short pwRingEchoOnTime, SWIGTYPE_p_unsigned_short pwRingEchoOffTime) {
    return shctiJNI.SsmGet2ndRingEchoTonePara(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwRingEchoOnTime), SWIGTYPE_p_unsigned_short.getCPtr(pwRingEchoOffTime));
  }

  public static int SsmSetBusyTonePeriodEx(int ch, int nType, int wMax, SWIGTYPE_p_unsigned_short pwPeriod) {
    return shctiJNI.SsmSetBusyTonePeriodEx(ch, nType, wMax, SWIGTYPE_p_unsigned_short.getCPtr(pwPeriod));
  }

  public static int SsmGetBusyTonePeriodEx(int ch, int nType, SWIGTYPE_p_unsigned_short pwPeriod) {
    return shctiJNI.SsmGetBusyTonePeriodEx(ch, nType, SWIGTYPE_p_unsigned_short.getCPtr(pwPeriod));
  }

  public static int SsmGetToneValue(int ch) {
    return shctiJNI.SsmGetToneValue(ch);
  }

  public static int SsmSetToneValue(int ch, int value) {
    return shctiJNI.SsmSetToneValue(ch, value);
  }

  public static int SsmGetOverallEnergyAllCh(int nBeginCh, int nChNum, SWIGTYPE_p_unsigned_long pdwEnergyTable) {
    return shctiJNI.SsmGetOverallEnergyAllCh(nBeginCh, nChNum, SWIGTYPE_p_unsigned_long.getCPtr(pdwEnergyTable));
  }

  public static int SsmSetNoSoundDtrmTime(int ch, long dwIsNoSoundDtrTime) {
    return shctiJNI.SsmSetNoSoundDtrmTime(ch, dwIsNoSoundDtrTime);
  }

  public static int SsmSetIsBargeInDtrmTime(int ch, int wIsBargeInDtrmTime) {
    return shctiJNI.SsmSetIsBargeInDtrmTime(ch, wIsBargeInDtrmTime);
  }

  public static int SsmSetBargeInSens(int ch, int nBargeInSens) {
    return shctiJNI.SsmSetBargeInSens(ch, nBargeInSens);
  }

  public static int SsmGetNoSoundTime(int ch) {
    return shctiJNI.SsmGetNoSoundTime(ch);
  }

  public static int SsmGetNoSoundDtrmTime(int ch) {
    return shctiJNI.SsmGetNoSoundDtrmTime(ch);
  }

  public static int SsmGetIsBargeInDtrmTime(int ch) {
    return shctiJNI.SsmGetIsBargeInDtrmTime(ch);
  }

  public static int SsmGetBargeInSens(int ch) {
    return shctiJNI.SsmGetBargeInSens(ch);
  }

  public static int SsmDetectBargeIn(int ch) {
    return shctiJNI.SsmDetectBargeIn(ch);
  }

  public static int SsmDetectNoSound(int ch) {
    return shctiJNI.SsmDetectNoSound(ch);
  }

  public static int SsmSetCalleeHookDetectP(int ch, int wMulti, int wValidTime) {
    return shctiJNI.SsmSetCalleeHookDetectP(ch, wMulti, wValidTime);
  }

  public static int SsmGetCalleeHookDetectP(int ch, SWIGTYPE_p_unsigned_short pwMulti, SWIGTYPE_p_unsigned_short pwValidTime) {
    return shctiJNI.SsmGetCalleeHookDetectP(ch, SWIGTYPE_p_unsigned_short.getCPtr(pwMulti), SWIGTYPE_p_unsigned_short.getCPtr(pwValidTime));
  }

  public static int SsmQueryOpRingDetect(int ch) {
    return shctiJNI.SsmQueryOpRingDetect(ch);
  }

  public static int SsmGetRingFlag(int ch) {
    return shctiJNI.SsmGetRingFlag(ch);
  }

  public static int SsmGetRingCount(int ch) {
    return shctiJNI.SsmGetRingCount(ch);
  }

  public static int SsmClearRingCount(int ch) {
    return shctiJNI.SsmClearRingCount(ch);
  }

  public static int SsmChkOpCallerId(int ch) {
    return shctiJNI.SsmChkOpCallerId(ch);
  }

  public static int SsmGetCallerId(int ch, String szCallerId) {
    return shctiJNI.SsmGetCallerId(ch, szCallerId);
  }

  public static String SsmGetCallerIdA(int ch) {
    return shctiJNI.SsmGetCallerIdA(ch);
  }

  public static int SsmGetCallerIdEx(int ch, String szCallerIdEx) {
    return shctiJNI.SsmGetCallerIdEx(ch, szCallerIdEx);
  }

  public static int SsmClearCallerId(int ch) {
    return shctiJNI.SsmClearCallerId(ch);
  }

  public static int SsmClearCallerIdEx(int ch) {
    return shctiJNI.SsmClearCallerIdEx(ch);
  }

  public static int SsmPickup(int ch) {
    return shctiJNI.SsmPickup(ch);
  }

  public static int SsmCheckActualPickup(int ch) {
    return shctiJNI.SsmCheckActualPickup(ch);
  }

  public static int SsmSetPickupNow(int ch, int bFlag) {
    return shctiJNI.SsmSetPickupNow(ch, bFlag);
  }

  public static int SsmHangup(int ch) {
    return shctiJNI.SsmHangup(ch);
  }

  public static int SsmAutoDial(int ch, String szPhoNum) {
    return shctiJNI.SsmAutoDial(ch, szPhoNum);
  }

  public static int SsmAutoDialEx(int ch, String szPhoNum, int wParam) {
    return shctiJNI.SsmAutoDialEx(ch, szPhoNum, wParam);
  }

  public static int SsmChkAutoDial(int ch) {
    return shctiJNI.SsmChkAutoDial(ch);
  }

  public static int SsmGetAutoDialFailureReason(int ch) {
    return shctiJNI.SsmGetAutoDialFailureReason(ch);
  }

  public static int SsmGetBlockReason(int ch) {
    return shctiJNI.SsmGetBlockReason(ch);
  }

  public static int SsmGetChState(int ch) {
    return shctiJNI.SsmGetChState(ch);
  }

  public static int SsmSetPlayDest(int ch, int nSelDest) {
    return shctiJNI.SsmSetPlayDest(ch, nSelDest);
  }

  public static int SsmSetRecBack(int ch, int nRecBack) {
    return shctiJNI.SsmSetRecBack(ch, nRecBack);
  }

  public static int SsmSearchIdleCallOutCh(int wSearchMode, long dwPrecedence) {
    return shctiJNI.SsmSearchIdleCallOutCh(wSearchMode, dwPrecedence);
  }

  public static int SsmSetAutoCallDirection(int ch, int bEnAutoCall, int nDirection) {
    return shctiJNI.SsmSetAutoCallDirection(ch, bEnAutoCall, nDirection);
  }

  public static int SsmGetAutoCallDirection(int ch, SWIGTYPE_p_int pnDirection) {
    return shctiJNI.SsmGetAutoCallDirection(ch, SWIGTYPE_p_int.getCPtr(pnDirection));
  }

  public static int SsmAppendPhoNum(int ch, String szPhoNum) {
    return shctiJNI.SsmAppendPhoNum(ch, szPhoNum);
  }

  public static int SsmGetPendingReason(int ch) {
    return shctiJNI.SsmGetPendingReason(ch);
  }

  public static int SsmGetChStateKeepTime(int ch) {
    return shctiJNI.SsmGetChStateKeepTime(ch);
  }

  public static int SsmGetPhoNumStr(int ch, String pszPhoNum) {
    return shctiJNI.SsmGetPhoNumStr(ch, pszPhoNum);
  }

  public static String SsmGetPhoNumStrA(int ch) {
    return shctiJNI.SsmGetPhoNumStrA(ch);
  }

  public static int SsmGetPhoNumLen(int ch) {
    return shctiJNI.SsmGetPhoNumLen(ch);
  }

  public static int SsmGet1stPhoNumStr(int ch, String pszPhoNum) {
    return shctiJNI.SsmGet1stPhoNumStr(ch, pszPhoNum);
  }

  public static String SsmGet1stPhoNumStrA(int ch) {
    return shctiJNI.SsmGet1stPhoNumStrA(ch);
  }

  public static int SsmGet1stPhoNumLen(int ch) {
    return shctiJNI.SsmGet1stPhoNumLen(ch);
  }

  public static int SsmEnableAutoSendKB(int ch, int bEnable) {
    return shctiJNI.SsmEnableAutoSendKB(ch, bEnable);
  }

  public static int SsmGetAutoSendKBFlag(int ch) {
    return shctiJNI.SsmGetAutoSendKBFlag(ch);
  }

  public static int SsmSetKB(int ch, short btSigKB) {
    return shctiJNI.SsmSetKB(ch, btSigKB);
  }

  public static int SsmSetKD(int ch, short btSigKD) {
    return shctiJNI.SsmSetKD(ch, btSigKD);
  }

  public static int SsmSetKA(int ch, short btSigKA) {
    return shctiJNI.SsmSetKA(ch, btSigKA);
  }

  public static int SsmSetTxCallerId(int ch, String pszTxCallerId) {
    return shctiJNI.SsmSetTxCallerId(ch, pszTxCallerId);
  }

  public static int SsmGetTxCallerId(int ch, String pszTxCallerId) {
    return shctiJNI.SsmGetTxCallerId(ch, pszTxCallerId);
  }

  public static int SsmGetKA(int ch) {
    return shctiJNI.SsmGetKA(ch);
  }

  public static int SsmGetKB(int ch) {
    return shctiJNI.SsmGetKB(ch);
  }

  public static int SsmGetKD(int ch) {
    return shctiJNI.SsmGetKD(ch);
  }

  public static int SsmBlockLocalCh(int ch) {
    return shctiJNI.SsmBlockLocalCh(ch);
  }

  public static int SsmUnblockLocalCh(int ch) {
    return shctiJNI.SsmUnblockLocalCh(ch);
  }

  public static int SsmQueryLocalChBlockState(int ch, SWIGTYPE_p_unsigned_long pdwBlockState) {
    return shctiJNI.SsmQueryLocalChBlockState(ch, SWIGTYPE_p_unsigned_long.getCPtr(pdwBlockState));
  }

  public static int SsmBlockLocalPCM(int nLocalPcmNo) {
    return shctiJNI.SsmBlockLocalPCM(nLocalPcmNo);
  }

  public static int SsmUnblockLocalPCM(int nLocalPcmNo) {
    return shctiJNI.SsmUnblockLocalPCM(nLocalPcmNo);
  }

  public static int SsmQueryLocalPCMBlockState(int nLocalPcmNo, SWIGTYPE_p_unsigned_long pdwBlockState) {
    return shctiJNI.SsmQueryLocalPCMBlockState(nLocalPcmNo, SWIGTYPE_p_unsigned_long.getCPtr(pdwBlockState));
  }

  public static int SsmQueryOpBlockRemoteCh(int ch) {
    return shctiJNI.SsmQueryOpBlockRemoteCh(ch);
  }

  public static int SsmBlockRemoteCh(int ch) {
    return shctiJNI.SsmBlockRemoteCh(ch);
  }

  public static int SsmUnblockRemoteCh(int ch) {
    return shctiJNI.SsmUnblockRemoteCh(ch);
  }

  public static int SsmGetRemoteChBlockStatus(int ch) {
    return shctiJNI.SsmGetRemoteChBlockStatus(ch);
  }

  public static int SsmBlockRemotePCM(int nLocalPcmNo, long dwBlockMode) {
    return shctiJNI.SsmBlockRemotePCM(nLocalPcmNo, dwBlockMode);
  }

  public static int SsmUnblockRemotePCM(int nLocalPcmNo, long dwUnblockMode) {
    return shctiJNI.SsmUnblockRemotePCM(nLocalPcmNo, dwUnblockMode);
  }

  public static int SsmGetRemotePCMBlockStatus(int nLocalPcmNo, long dwBlockMode) {
    return shctiJNI.SsmGetRemotePCMBlockStatus(nLocalPcmNo, dwBlockMode);
  }

  public static int SsmGetWaitAutoDialAnswerTime(SWIGTYPE_p_unsigned_short pwSeconds) {
    return shctiJNI.SsmGetWaitAutoDialAnswerTime(SWIGTYPE_p_unsigned_short.getCPtr(pwSeconds));
  }

  public static int SsmSetWaitAutoDialAnswerTime(int wSeconds) {
    return shctiJNI.SsmSetWaitAutoDialAnswerTime(wSeconds);
  }

  public static int SsmStartPickupAnalyze(int ch) {
    return shctiJNI.SsmStartPickupAnalyze(ch);
  }

  public static int SsmGetPickup(int ch) {
    return shctiJNI.SsmGetPickup(ch);
  }

  public static int SsmQueryOpEchoCanceller(int ch) {
    return shctiJNI.SsmQueryOpEchoCanceller(ch);
  }

  public static int SsmSetEchoCanceller(int ch, int bRun) {
    return shctiJNI.SsmSetEchoCanceller(ch, bRun);
  }

  public static int SsmGetEchoCancellerState(int ch) {
    return shctiJNI.SsmGetEchoCancellerState(ch);
  }

  public static int SsmSetEchoCancellerStudy(int ch, int bRun) {
    return shctiJNI.SsmSetEchoCancellerStudy(ch, bRun);
  }

  public static int SsmGetEchoCancellerStudyState(int ch) {
    return shctiJNI.SsmGetEchoCancellerStudyState(ch);
  }

  public static int SsmGetEchoCancellerRatio(int ch) {
    return shctiJNI.SsmGetEchoCancellerRatio(ch);
  }

  public static int SsmSaveEchoCancellerPara(int ch) {
    return shctiJNI.SsmSaveEchoCancellerPara(ch);
  }

  public static int SsmSetEchoCancelDelaySize(int ch, int wSize) {
    return shctiJNI.SsmSetEchoCancelDelaySize(ch, wSize);
  }

  public static int SsmGetEchoCancelDelaySize(int ch) {
    return shctiJNI.SsmGetEchoCancelDelaySize(ch);
  }

  public static int SsmListenTo(int ch1, int ch2) {
    return shctiJNI.SsmListenTo(ch1, ch2);
  }

  public static int SsmListenToEx(int ch1, int nVolume1, int ch2) {
    return shctiJNI.SsmListenToEx(ch1, nVolume1, ch2);
  }

  public static int SsmStopListenTo(int ch1, int ch2) {
    return shctiJNI.SsmStopListenTo(ch1, ch2);
  }

  public static int SsmTalkWith(int ch1, int ch2) {
    return shctiJNI.SsmTalkWith(ch1, ch2);
  }

  public static int SsmTalkWithEx(int ch1, int nVlm1, int ch2, int nVlm2) {
    return shctiJNI.SsmTalkWithEx(ch1, nVlm1, ch2, nVlm2);
  }

  public static int SsmStopTalkWith(int ch1, int ch2) {
    return shctiJNI.SsmStopTalkWith(ch1, ch2);
  }

  public static void PlayListen(long dwBId, long ch) {
    shctiJNI.PlayListen(dwBId, ch);
  }

  public static void PlayListenNew(long dwSpeakerCh, long dwMonitorCh) {
    shctiJNI.PlayListenNew(dwSpeakerCh, dwMonitorCh);
  }

  public static void StopListen(long dwBId) {
    shctiJNI.StopListen(dwBId);
  }

  public static void StopListenNew(long dwSpeakerCh) {
    shctiJNI.StopListenNew(dwSpeakerCh);
  }

  public static int SsmLinkFrom(int ch1, int ch2) {
    return shctiJNI.SsmLinkFrom(ch1, ch2);
  }

  public static int SsmStopLinkFrom(int ch1, int ch2) {
    return shctiJNI.SsmStopLinkFrom(ch1, ch2);
  }

  public static int SsmLinkFromEx(int ch1, int nVolume1, int ch2) {
    return shctiJNI.SsmLinkFromEx(ch1, nVolume1, ch2);
  }

  public static int SsmLinkFromAllCh(int ch, int nVolume, SWIGTYPE_p_int nListenerTable, int nListenerNum) {
    return shctiJNI.SsmLinkFromAllCh(ch, nVolume, SWIGTYPE_p_int.getCPtr(nListenerTable), nListenerNum);
  }

  public static int SsmUnLinkFromAllCh(int ch, SWIGTYPE_p_int nListenerTable, int nListenerNum) {
    return shctiJNI.SsmUnLinkFromAllCh(ch, SWIGTYPE_p_int.getCPtr(nListenerTable), nListenerNum);
  }

  public static int SsmLinkToBus(int ch, int ts) {
    return shctiJNI.SsmLinkToBus(ch, ts);
  }

  public static int SsmUnLinkToBus(int ch, int ts) {
    return shctiJNI.SsmUnLinkToBus(ch, ts);
  }

  public static int SsmLinkFromBus(int ts, int ch) {
    return shctiJNI.SsmLinkFromBus(ts, ch);
  }

  public static int SsmLinkFromBusEx(int ts, int ch, int vlm) {
    return shctiJNI.SsmLinkFromBusEx(ts, ch, vlm);
  }

  public static int SsmUnLinkFromBus(int ts, int ch) {
    return shctiJNI.SsmUnLinkFromBus(ts, ch);
  }

  public static int SsmListenToPlay(int ch1, int vlm1, int ch2) {
    return shctiJNI.SsmListenToPlay(ch1, vlm1, ch2);
  }

  public static int SsmUnListenToPlay(int ch1, int ch2) {
    return shctiJNI.SsmUnListenToPlay(ch1, ch2);
  }

  public static int SsmCreateConfGroup(int nMaxMember, int nMaxSpeaker, int nMaxSpeaking, int nMaxSilenceTime) {
    return shctiJNI.SsmCreateConfGroup(nMaxMember, nMaxSpeaker, nMaxSpeaking, nMaxSilenceTime);
  }

  public static int SsmFreeConfGroup(int nGrpId) {
    return shctiJNI.SsmFreeConfGroup(nGrpId);
  }

  public static int SsmJoinConfGroup(int nGrpId, int ch, int wJoinMode, int nMixerVolume, int bCreateAlways, int bExitGrpAlways) {
    return shctiJNI.SsmJoinConfGroup(nGrpId, ch, wJoinMode, nMixerVolume, bCreateAlways, bExitGrpAlways);
  }

  public static int SsmExitConfGroup(int ch, int bFreeGrpAlways) {
    return shctiJNI.SsmExitConfGroup(ch, bFreeGrpAlways);
  }

  public static int SsmGetConfCfgInfo(SWIGTYPE_p_unsigned_short pwMaxMember, SWIGTYPE_p_unsigned_short pwMaxSpeaker, SWIGTYPE_p_unsigned_short pwMaxSpeaking, SWIGTYPE_p_unsigned_short pwMaxSilenceTime) {
    return shctiJNI.SsmGetConfCfgInfo(SWIGTYPE_p_unsigned_short.getCPtr(pwMaxMember), SWIGTYPE_p_unsigned_short.getCPtr(pwMaxSpeaker), SWIGTYPE_p_unsigned_short.getCPtr(pwMaxSpeaking), SWIGTYPE_p_unsigned_short.getCPtr(pwMaxSilenceTime));
  }

  public static int SsmGetTotalConfGroup() {
    return shctiJNI.SsmGetTotalConfGroup();
  }

  public static int SsmGetConfGrpId(SWIGTYPE_p_int pnGrpId) {
    return shctiJNI.SsmGetConfGrpId(SWIGTYPE_p_int.getCPtr(pnGrpId));
  }

  public static int SsmGetConfGrpCfgInfo(int nGrpId, SWIGTYPE_p_unsigned_short pwMaxMember, SWIGTYPE_p_unsigned_short pwMaxSpeaker, SWIGTYPE_p_unsigned_short pwMaxSpeaking, SWIGTYPE_p_unsigned_short pwMaxSilenceTime) {
    return shctiJNI.SsmGetConfGrpCfgInfo(nGrpId, SWIGTYPE_p_unsigned_short.getCPtr(pwMaxMember), SWIGTYPE_p_unsigned_short.getCPtr(pwMaxSpeaker), SWIGTYPE_p_unsigned_short.getCPtr(pwMaxSpeaking), SWIGTYPE_p_unsigned_short.getCPtr(pwMaxSilenceTime));
  }

  public static int SsmGetConfGrpInfo(int nGrpId, SWIGTYPE_p_unsigned_short pwTotalMember, SWIGTYPE_p_unsigned_short pwTotalSpeaker, SWIGTYPE_p_unsigned_short pwTotalSpeaking) {
    return shctiJNI.SsmGetConfGrpInfo(nGrpId, SWIGTYPE_p_unsigned_short.getCPtr(pwTotalMember), SWIGTYPE_p_unsigned_short.getCPtr(pwTotalSpeaker), SWIGTYPE_p_unsigned_short.getCPtr(pwTotalSpeaking));
  }

  public static int SsmGetConfGrpMmbrId(int nGrpId, SWIGTYPE_p_int pnMmbrId) {
    return shctiJNI.SsmGetConfGrpMmbrId(nGrpId, SWIGTYPE_p_int.getCPtr(pnMmbrId));
  }

  public static int SsmGetConfGrpMmbrInfo(int nGrpId, int nMmbrId, SWIGTYPE_p_int pnAppCh, SWIGTYPE_p_unsigned_short pwJoinMode, SWIGTYPE_p_unsigned_short pwIsSpeaking, SWIGTYPE_p_unsigned_long pdwSilenceTime) {
    return shctiJNI.SsmGetConfGrpMmbrInfo(nGrpId, nMmbrId, SWIGTYPE_p_int.getCPtr(pnAppCh), SWIGTYPE_p_unsigned_short.getCPtr(pwJoinMode), SWIGTYPE_p_unsigned_short.getCPtr(pwIsSpeaking), SWIGTYPE_p_unsigned_long.getCPtr(pdwSilenceTime));
  }

  public static int SsmGetConfChInfo(int ch, SWIGTYPE_p_int pnGrpId, SWIGTYPE_p_int pnMmbrId, SWIGTYPE_p_unsigned_short pwJoinMode, SWIGTYPE_p_unsigned_short pwIsSpeaking, SWIGTYPE_p_unsigned_long pdwSilenceTime) {
    return shctiJNI.SsmGetConfChInfo(ch, SWIGTYPE_p_int.getCPtr(pnGrpId), SWIGTYPE_p_int.getCPtr(pnMmbrId), SWIGTYPE_p_unsigned_short.getCPtr(pwJoinMode), SWIGTYPE_p_unsigned_short.getCPtr(pwIsSpeaking), SWIGTYPE_p_unsigned_long.getCPtr(pdwSilenceTime));
  }

  public static long InitCard(long add1, long add2, long add3, long add4, long add5, long add6, long add7, long add8, long intno) {
    return shctiJNI.InitCard(add1, add2, add3, add4, add5, add6, add7, add8, intno);
  }

  public static void ShutCard() {
    shctiJNI.ShutCard();
  }

  public static long StartRecordFile(long ch, String fliename) {
    return shctiJNI.StartRecordFile(ch, fliename);
  }

  public static void StopRecordFile(long ch) {
    shctiJNI.StopRecordFile(ch);
  }

  public static void PauseRecord(long ch) {
    shctiJNI.PauseRecord(ch);
  }

  public static void RestartRecord(long ch) {
    shctiJNI.RestartRecord(ch);
  }

  public static long GetRecordTime(long ch) {
    return shctiJNI.GetRecordTime(ch);
  }

  public static long StartPlayFile(long ch, String filename) {
    return shctiJNI.StartPlayFile(ch, filename);
  }

  public static void StopPlayFile(long ch) {
    shctiJNI.StopPlayFile(ch);
  }

  public static long CheckPlayingEnd(long ch) {
    return shctiJNI.CheckPlayingEnd(ch);
  }

  public static void PausePlay(long ch) {
    shctiJNI.PausePlay(ch);
  }

  public static void RestartPlay(long ch) {
    shctiJNI.RestartPlay(ch);
  }

  public static void FastPlay(long ch) {
    shctiJNI.FastPlay(ch);
  }

  public static void BackPlay(long ch) {
    shctiJNI.BackPlay(ch);
  }

  public static long GetPlayTime(long ch) {
    return shctiJNI.GetPlayTime(ch);
  }

  public static long GetPlayPercent(long ch) {
    return shctiJNI.GetPlayPercent(ch);
  }

  public static void SetPlayTime(long ch, long time) {
    shctiJNI.SetPlayTime(ch, time);
  }

  public static void SetPlayPercent(long ch, long percent) {
    shctiJNI.SetPlayPercent(ch, percent);
  }

  public static long LoadIndexFile(long segno, String filename, long startadr, long length) {
    return shctiJNI.LoadIndexFile(segno, filename, startadr, length);
  }

  public static void FreeIndexMem(long segno) {
    shctiJNI.FreeIndexMem(segno);
  }

  public static void PlayIndex(long ch, String segstring) {
    shctiJNI.PlayIndex(ch, segstring);
  }

  public static void StopIndex(long ch) {
    shctiJNI.StopIndex(ch);
  }

  public static void DTMFStop(long ch, long if_stop) {
    shctiJNI.DTMFStop(ch, if_stop);
  }

  public static long GetDTMF(long ch) {
    return shctiJNI.GetDTMF(ch);
  }

  public static long GetDTMFStr(long ch, String buf) {
    return shctiJNI.GetDTMFStr(ch, buf);
  }

  public static void ClearDTMFBuf(long ch) {
    shctiJNI.ClearDTMFBuf(ch);
  }

  public static long DetectRing(long ch) {
    return shctiJNI.DetectRing(ch);
  }

  public static void ClearRing(long ch) {
    shctiJNI.ClearRing(ch);
  }

  public static void HangUp(long ch) {
    shctiJNI.HangUp(ch);
  }

  public static void PickUp(long ch) {
    shctiJNI.PickUp(ch);
  }

  public static long DetectInter(long ch) {
    return shctiJNI.DetectInter(ch);
  }

  public static long GetFlash(long ch) {
    return shctiJNI.GetFlash(ch);
  }

  public static void SetFlashTime(int time) {
    shctiJNI.SetFlashTime(time);
  }

  public static long ToneCheck(long ch) {
    return shctiJNI.ToneCheck(ch);
  }

  public static long GetBusyLen(long ch) {
    return shctiJNI.GetBusyLen(ch);
  }

  public static void DTMFDial(long ch, String dialstring) {
    shctiJNI.DTMFDial(ch, dialstring);
  }

  public static long DTMFDialEnd(long ch) {
    return shctiJNI.DTMFDialEnd(ch);
  }

  public static void Flash(long ch, long time) {
    shctiJNI.Flash(ch, time);
  }

  public static void SetPlayVolume(long ch, int volume) {
    shctiJNI.SetPlayVolume(ch, volume);
  }

  public static void SetRecVolume(long ch, int volume) {
    shctiJNI.SetRecVolume(ch, volume);
  }

  public static long GetCallerId(long ch, String buf) {
    return shctiJNI.GetCallerId(ch, buf);
  }

  public static void SetPickSens(long piont) {
    shctiJNI.SetPickSens(piont);
  }

  public static long GetPickUp(long ch) {
    return shctiJNI.GetPickUp(ch);
  }

  public static long GetNum(long ch, String buf, long time, long len, int end_char) {
    return shctiJNI.GetNum(ch, buf, time, len, end_char);
  }

  public static void SetWorkMode(int Mode) {
    shctiJNI.SetWorkMode(Mode);
  }

  public static void SetUserCard(long addr1, long addr2, long addr3, long addr4, long addr5, long addr6, long addr7, long addr8) {
    shctiJNI.SetUserCard(addr1, addr2, addr3, addr4, addr5, addr6, addr7, addr8);
  }

  public static void SendBusyTone(int ch) {
    shctiJNI.SendBusyTone(ch);
  }

  public static void SendRingEchoTone(int ch) {
    shctiJNI.SendRingEchoTone(ch);
  }

  public static void SendDialTone(int ch) {
    shctiJNI.SendDialTone(ch);
  }

  public static void StopSendTone(int ch) {
    shctiJNI.StopSendTone(ch);
  }

  public static void StartSendRing(int ch) {
    shctiJNI.StartSendRing(ch);
  }

  public static void StopSendRing(int ch) {
    shctiJNI.StopSendRing(ch);
  }

  public static int Link2Ch(int ch1, int ch2) {
    return shctiJNI.Link2Ch(ch1, ch2);
  }

  public static void UnLink2Ch(int ch1, int ch2) {
    shctiJNI.UnLink2Ch(ch1, ch2);
  }

  public static int Link3Ch(int ch1, int ch2, int ch3) {
    return shctiJNI.Link3Ch(ch1, ch2, ch3);
  }

  public static void UnLink3Ch(int ch1, int ch2, int ch3) {
    shctiJNI.UnLink3Ch(ch1, ch2, ch3);
  }

  public static int ListenFromCh(int ch1, int ch2) {
    return shctiJNI.ListenFromCh(ch1, ch2);
  }

  public static void StopListenFromCh(int ch1, int ch2) {
    shctiJNI.StopListenFromCh(ch1, ch2);
  }

  public static void SetDelay(long ch, long delay) {
    shctiJNI.SetDelay(ch, delay);
  }

  public static void SetLevel(long ch, long level) {
    shctiJNI.SetLevel(ch, level);
  }

  public static long DetectSound(long ch) {
    return shctiJNI.DetectSound(ch);
  }

  public static long GetFax11(long ch) {
    return shctiJNI.GetFax11(ch);
  }

  public static long GetFax21(long ch) {
    return shctiJNI.GetFax21(ch);
  }

  public static long GetRing(long ch) {
    return shctiJNI.GetRing(ch);
  }

  public static void SetDialSpeed(long point) {
    shctiJNI.SetDialSpeed(point);
  }

  public static void GetErrorMsg(String buf) {
    shctiJNI.GetErrorMsg(buf);
  }

  public static long SetMaxSeg(long inmaxsegment) {
    return shctiJNI.SetMaxSeg(inmaxsegment);
  }

  public static void PauseCard() {
    shctiJNI.PauseCard();
  }

  public static void RestartCard() {
    shctiJNI.RestartCard();
  }

  public static long GetLevel(long ch) {
    return shctiJNI.GetLevel(ch);
  }

  public static void SetJudge(long ch, long Judge) {
    shctiJNI.SetJudge(ch, Judge);
  }

  public static int SsmQueryOpADC(int ch) {
    return shctiJNI.SsmQueryOpADC(ch);
  }

  public static int SsmGetLineVoltage(int ch) {
    return shctiJNI.SsmGetLineVoltage(ch);
  }

  public static int SsmSetDtrmLineVoltage(int ch, int wDtrmValtage) {
    return shctiJNI.SsmSetDtrmLineVoltage(ch, wDtrmValtage);
  }

  public static int SsmGetDtrmLineVoltage(int ch) {
    return shctiJNI.SsmGetDtrmLineVoltage(ch);
  }

  public static long DetectPickUp(long ch) {
    return shctiJNI.DetectPickUp(ch);
  }

  public static long DetectEmpty(long ch) {
    return shctiJNI.DetectEmpty(ch);
  }

  public static void SetSoundJudgeLevel(long ch, long level) {
    shctiJNI.SetSoundJudgeLevel(ch, level);
  }

  public static long GetSoundJudgeLevel(long ch) {
    return shctiJNI.GetSoundJudgeLevel(ch);
  }

  public static int SsmQueryOpMicGain(int ch) {
    return shctiJNI.SsmQueryOpMicGain(ch);
  }

  public static int SsmSetMicGain(int ch, int nGain) {
    return shctiJNI.SsmSetMicGain(ch, nGain);
  }

  public static int SsmGetMicGain(int ch) {
    return shctiJNI.SsmGetMicGain(ch);
  }

  public static int SsmSetIgnoreLineVoltage(int ch, int bEnable) {
    return shctiJNI.SsmSetIgnoreLineVoltage(ch, bEnable);
  }

  public static int SsmGetIgnoreLineVoltage(int ch) {
    return shctiJNI.SsmGetIgnoreLineVoltage(ch);
  }

  public static void SetVolume(long dwBoardId, long dwVolume) {
    shctiJNI.SetVolume(dwBoardId, dwVolume);
  }

  public static int SsmQueryOpPowerAmp(int ch) {
    return shctiJNI.SsmQueryOpPowerAmp(ch);
  }

  public static int SsmSetPowerAmpVlm(int ch, int nVolume) {
    return shctiJNI.SsmSetPowerAmpVlm(ch, nVolume);
  }

  public static long GetFZCount(long ch) {
    return shctiJNI.GetFZCount(ch);
  }

  public static int SsmQueryOpPolarRvrs(int ch) {
    return shctiJNI.SsmQueryOpPolarRvrs(ch);
  }

  public static int SsmGetPolarRvrsCount(int ch) {
    return shctiJNI.SsmGetPolarRvrsCount(ch);
  }

  public static int SsmGetPolarState(int ch) {
    return shctiJNI.SsmGetPolarState(ch);
  }

  public static int SsmSetPolarState(int ch, int nPolar) {
    return shctiJNI.SsmSetPolarState(ch, nPolar);
  }

  public static int SsmSetUnimoduleState(int ch, int nLink) {
    return shctiJNI.SsmSetUnimoduleState(ch, nLink);
  }

  public static int SsmQueryOpSS1(int ch) {
    return shctiJNI.SsmQueryOpSS1(ch);
  }

  public static int SsmSendCAS(int ch, short btCas) {
    return shctiJNI.SsmSendCAS(ch, btCas);
  }

  public static int SsmGetCAS(int ch) {
    return shctiJNI.SsmGetCAS(ch);
  }

  public static int SsmSetRxR2Mode(int ch, int nMode, int bEnable) {
    return shctiJNI.SsmSetRxR2Mode(ch, nMode, bEnable);
  }

  public static int SsmGetR2(int ch) {
    return shctiJNI.SsmGetR2(ch);
  }

  public static int SsmSendR2(int ch, int nMode, short btR2) {
    return shctiJNI.SsmSendR2(ch, nMode, btR2);
  }

  public static int SsmStopSendR2(int ch) {
    return shctiJNI.SsmStopSendR2(ch);
  }

  public static int SsmGetSendingCAS(int ch) {
    return shctiJNI.SsmGetSendingCAS(ch);
  }

  public static int SsmGetSendingR2(int ch, SWIGTYPE_p_int pnMode, SWIGTYPE_p_unsigned_char pbtR2) {
    return shctiJNI.SsmGetSendingR2(ch, SWIGTYPE_p_int.getCPtr(pnMode), SWIGTYPE_p_unsigned_char.getCPtr(pbtR2));
  }

  public static int SsmGetMaxPcm() {
    return shctiJNI.SsmGetMaxPcm();
  }

  public static int SsmGetPcmInfo(int nPcmNo, SWIGTYPE_p_int pnSSxMode, SWIGTYPE_p_int pnBoardId, SWIGTYPE_p_int pnBoardPcmNo, SWIGTYPE_p_int pnUsePcmTS16, SWIGTYPE_p_unsigned_long pdwRcvrMode, SWIGTYPE_p_unsigned_long pdwEnableAutoCall, SWIGTYPE_p_unsigned_long pdwAutoCallDirection) {
    return shctiJNI.SsmGetPcmInfo(nPcmNo, SWIGTYPE_p_int.getCPtr(pnSSxMode), SWIGTYPE_p_int.getCPtr(pnBoardId), SWIGTYPE_p_int.getCPtr(pnBoardPcmNo), SWIGTYPE_p_int.getCPtr(pnUsePcmTS16), SWIGTYPE_p_unsigned_long.getCPtr(pdwRcvrMode), SWIGTYPE_p_unsigned_long.getCPtr(pdwEnableAutoCall), SWIGTYPE_p_unsigned_long.getCPtr(pdwAutoCallDirection));
  }

  public static int SsmGetPcmLinkStatus(int nPcmNo, SWIGTYPE_p_unsigned_short pwPcmLinkStatus) {
    return shctiJNI.SsmGetPcmLinkStatus(nPcmNo, SWIGTYPE_p_unsigned_short.getCPtr(pwPcmLinkStatus));
  }

  public static int SsmPcmTsToCh(int nLocalPcmNo, int nTs) {
    return shctiJNI.SsmPcmTsToCh(nLocalPcmNo, nTs);
  }

  public static int SsmChToPcmTs(int ch, SWIGTYPE_p_int pnLocalPcmNo, SWIGTYPE_p_int pnTs) {
    return shctiJNI.SsmChToPcmTs(ch, SWIGTYPE_p_int.getCPtr(pnLocalPcmNo), SWIGTYPE_p_int.getCPtr(pnTs));
  }

  public static int SsmSetFskPara(int nFreqBit0, int nFreqBit1, int nBaudrate, int nMdlAmp) {
    return shctiJNI.SsmSetFskPara(nFreqBit0, nFreqBit1, nBaudrate, nMdlAmp);
  }

  public static int SsmGetFskPara(SWIGTYPE_p_int pnFreqBit0, SWIGTYPE_p_int pnFreqBit1, SWIGTYPE_p_int pnBaudrate, SWIGTYPE_p_int pnMdlAmp) {
    return shctiJNI.SsmGetFskPara(SWIGTYPE_p_int.getCPtr(pnFreqBit0), SWIGTYPE_p_int.getCPtr(pnFreqBit1), SWIGTYPE_p_int.getCPtr(pnBaudrate), SWIGTYPE_p_int.getCPtr(pnMdlAmp));
  }

  public static int SsmTransFskData(SWIGTYPE_p_unsigned_char pS, int nSrcLen, int nSyncLen, int nSyncOffLen, SWIGTYPE_p_unsigned_char pD) {
    return shctiJNI.SsmTransFskData(SWIGTYPE_p_unsigned_char.getCPtr(pS), nSrcLen, nSyncLen, nSyncOffLen, SWIGTYPE_p_unsigned_char.getCPtr(pD));
  }

  public static int SsmStartSendFSK(int ch, String pBuf, long dwMaxBit) {
    return shctiJNI.SsmStartSendFSK(ch, pBuf, dwMaxBit);
  }

  public static int SsmCheckSendFsk(int ch) {
    return shctiJNI.SsmCheckSendFsk(ch);
  }

  public static int SsmStopSendFsk(int ch) {
    return shctiJNI.SsmStopSendFsk(ch);
  }

  public static int SsmStartRcvFSK_II(int ch, int wTimeOut, int wMaxLen, SWIGTYPE_p_unsigned_char pucMarkCodeBuf, short ucMarkCodeCount) {
    return shctiJNI.SsmStartRcvFSK_II(ch, wTimeOut, wMaxLen, SWIGTYPE_p_unsigned_char.getCPtr(pucMarkCodeBuf), ucMarkCodeCount);
  }

  public static int SsmStartRcvFSK(int ch, int wTimeOut, int wMaxLen, short ucEndCode, int wEndCodeCount) {
    return shctiJNI.SsmStartRcvFSK(ch, wTimeOut, wMaxLen, ucEndCode, wEndCodeCount);
  }

  public static int SsmClearRcvFSKBuf(int ch) {
    return shctiJNI.SsmClearRcvFSKBuf(ch);
  }

  public static int SsmCheckRcvFSK(int ch) {
    return shctiJNI.SsmCheckRcvFSK(ch);
  }

  public static int SsmGetRcvFSK(int ch, SWIGTYPE_p_unsigned_char pucBuf) {
    return shctiJNI.SsmGetRcvFSK(ch, SWIGTYPE_p_unsigned_char.getCPtr(pucBuf));
  }

  public static int SsmStopRcvFSK(int ch) {
    return shctiJNI.SsmStopRcvFSK(ch);
  }

  public static int SsmSendSs7Msu(int wMsuLength, SWIGTYPE_p_unsigned_char pucMsuBuf) {
    return shctiJNI.SsmSendSs7Msu(wMsuLength, SWIGTYPE_p_unsigned_char.getCPtr(pucMsuBuf));
  }

  public static int SsmGetSs7Msu(SWIGTYPE_p_p_unsigned_char ppucMsuBuf) {
    return shctiJNI.SsmGetSs7Msu(SWIGTYPE_p_p_unsigned_char.getCPtr(ppucMsuBuf));
  }

  public static int SsmGetSs7Mtp2Msu(SWIGTYPE_p_unsigned_char pucPara, SWIGTYPE_p_p_unsigned_char ppucMsuBuf) {
    return shctiJNI.SsmGetSs7Mtp2Msu(SWIGTYPE_p_unsigned_char.getCPtr(pucPara), SWIGTYPE_p_p_unsigned_char.getCPtr(ppucMsuBuf));
  }

  public static int SsmGetMtp3State() {
    return shctiJNI.SsmGetMtp3State();
  }

  public static int SsmGetMtp3StateEx(int nDpcNo) {
    return shctiJNI.SsmGetMtp3StateEx(nDpcNo);
  }

  public static int SsmGetMtp2Status(int nLinkNum) {
    return shctiJNI.SsmGetMtp2Status(nLinkNum);
  }

  public static int SsmSetISUPCAT(int nch, short ucCallerCAT) {
    return shctiJNI.SsmSetISUPCAT(nch, ucCallerCAT);
  }

  public static int SsmFaxGetChStateMsg(int ch, String buf) {
    return shctiJNI.SsmFaxGetChStateMsg(ch, buf);
  }

  public static int SsmFaxGetPages(int ch) {
    return shctiJNI.SsmFaxGetPages(ch);
  }

  public static int SsmFaxStartReceive(int ch, String filename) {
    return shctiJNI.SsmFaxStartReceive(ch, filename);
  }

  public static int SsmFaxStartSend(int ch, String filename) {
    return shctiJNI.SsmFaxStartSend(ch, filename);
  }

  public static int SsmFaxStop(int ch) {
    return shctiJNI.SsmFaxStop(ch);
  }

  public static void SsmFaxSetMaxSpeed(int speed) {
    shctiJNI.SsmFaxSetMaxSpeed(speed);
  }

  public static int SsmFaxCheckEnd(int ch) {
    return shctiJNI.SsmFaxCheckEnd(ch);
  }

  public static int SsmFaxSetID(int ch, String myid) {
    return shctiJNI.SsmFaxSetID(ch, myid);
  }

  public static int SsmFaxGetID(int ch, String myid) {
    return shctiJNI.SsmFaxGetID(ch, myid);
  }

  public static int SsmFaxSetSendMode(int ch, int mode) {
    return shctiJNI.SsmFaxSetSendMode(ch, mode);
  }

  public static int SsmFaxGetRcvBytes(int ch) {
    return shctiJNI.SsmFaxGetRcvBytes(ch);
  }

  public static int SsmFaxGetSendBytes(int ch) {
    return shctiJNI.SsmFaxGetSendBytes(ch);
  }

  public static int SsmFaxAppendSend(int ch, String filename) {
    return shctiJNI.SsmFaxAppendSend(ch, filename);
  }

  public static int SsmFaxStartSendEx(int ch, String filename, int nStartPage, int nEndPage) {
    return shctiJNI.SsmFaxStartSendEx(ch, filename, nStartPage, nEndPage);
  }

  public static int SsmFaxSendMultiFile(int ch, String szFilePath, String szFileName) {
    return shctiJNI.SsmFaxSendMultiFile(ch, szFilePath, szFileName);
  }

  public static int SsmFaxSendMultiFileEx(int ch, FAX_FILE_SCT pV, int nNum) {
    return shctiJNI.SsmFaxSendMultiFileEx(ch, FAX_FILE_SCT.getCPtr(pV), pV, nNum);
  }

  public static int SsmEnableCh(int ch) {
    return shctiJNI.SsmEnableCh(ch);
  }

  public static int SsmDisableCh(int ch) {
    return shctiJNI.SsmDisableCh(ch);
  }

  public static int SsmResetCh(int ch) {
    return shctiJNI.SsmResetCh(ch);
  }

  public static int SsmCheckResetCh(int ch) {
    return shctiJNI.SsmCheckResetCh(ch);
  }

  public static int SsmGetLSR(int ch, SWIGTYPE_p_unsigned_char retu) {
    return shctiJNI.SsmGetLSR(ch, SWIGTYPE_p_unsigned_char.getCPtr(retu));
  }

  public static int SsmGetMSR(int ch, SWIGTYPE_p_unsigned_char retu) {
    return shctiJNI.SsmGetMSR(ch, SWIGTYPE_p_unsigned_char.getCPtr(retu));
  }

  public static int SsmGetRTS(int ch) {
    return shctiJNI.SsmGetRTS(ch);
  }

  public static int SsmGetCTS(int ch) {
    return shctiJNI.SsmGetCTS(ch);
  }

  public static int SsmGetOH(int ch) {
    return shctiJNI.SsmGetOH(ch);
  }

  public static int SsmDetectCarry(int ch) {
    return shctiJNI.SsmDetectCarry(ch);
  }

  public static int SsmFaxGetChState(int ch, SWIGTYPE_p_unsigned_short buf) {
    return shctiJNI.SsmFaxGetChState(ch, SWIGTYPE_p_unsigned_short.getCPtr(buf));
  }

  public static int SsmReadRxBuf(int ch, int nLen, String lpcRxBuf) {
    return shctiJNI.SsmReadRxBuf(ch, nLen, lpcRxBuf);
  }

  public static int SsmGetRxBufLen(int ch) {
    return shctiJNI.SsmGetRxBufLen(ch);
  }

  public static void SsmClearRxBuf(int ch) {
    shctiJNI.SsmClearRxBuf(ch);
  }

  public static int SsmWriteTxBuf(int ch, int nLen, String lpcTxBuf) {
    return shctiJNI.SsmWriteTxBuf(ch, nLen, lpcTxBuf);
  }

  public static int SsmWriteTxBuf_S(int ch, String s) {
    return shctiJNI.SsmWriteTxBuf_S(ch, s);
  }

  public static int SsmWriteTxBuf_C(int ch, char buf) {
    return shctiJNI.SsmWriteTxBuf_C(ch, buf);
  }

  public static int SsmGetTxBufRemain(int ch) {
    return shctiJNI.SsmGetTxBufRemain(ch);
  }

  public static int SsmGetTxBufLen(int ch) {
    return shctiJNI.SsmGetTxBufLen(ch);
  }

  public static void SsmClearTxBuf(int ch) {
    shctiJNI.SsmClearTxBuf(ch);
  }

  public static int SsmISDNSetDialSubAddr(int ch, String lpSubAddress) {
    return shctiJNI.SsmISDNSetDialSubAddr(ch, lpSubAddress);
  }

  public static int SsmISDNSetTxSubAddr(int ch, String lpSubAddress) {
    return shctiJNI.SsmISDNSetTxSubAddr(ch, lpSubAddress);
  }

  public static int SsmISDNGetTxCallerSubAddr(int ch, String lpSubAddress) {
    return shctiJNI.SsmISDNGetTxCallerSubAddr(ch, lpSubAddress);
  }

  public static int SsmISDNGetSubAddr(int ch, String lpSubAddress) {
    return shctiJNI.SsmISDNGetSubAddr(ch, lpSubAddress);
  }

  public static int SsmISDNGetCallerSubAddr(int ch, String lpSubAddress) {
    return shctiJNI.SsmISDNGetCallerSubAddr(ch, lpSubAddress);
  }

  public static int SsmISDNGetDisplayMsg(int ch, String lpDispMsg) {
    return shctiJNI.SsmISDNGetDisplayMsg(ch, lpDispMsg);
  }

  public static int SsmISDNSetHangupRzn(int ch, int nReason) {
    return shctiJNI.SsmISDNSetHangupRzn(ch, nReason);
  }

  public static int SsmISDNGetStatus(int nPcmNo, SWIGTYPE_p_int pL3Start, SWIGTYPE_p_int pL2DStatus, SWIGTYPE_p_int pL2D_L3Atom, SWIGTYPE_p_int pL3_L2DAtom, SWIGTYPE_p_int pRef_ind) {
    return shctiJNI.SsmISDNGetStatus(nPcmNo, SWIGTYPE_p_int.getCPtr(pL3Start), SWIGTYPE_p_int.getCPtr(pL2DStatus), SWIGTYPE_p_int.getCPtr(pL2D_L3Atom), SWIGTYPE_p_int.getCPtr(pL3_L2DAtom), SWIGTYPE_p_int.getCPtr(pRef_ind));
  }

  public static int SsmStartRecognize(int ch, int grammarid, int max_time) {
    return shctiJNI.SsmStartRecognize(ch, grammarid, max_time);
  }

  public static int SsmGetResultCount(int ch) {
    return shctiJNI.SsmGetResultCount(ch);
  }

  public static int SsmGetCurSens(int ch) {
    return shctiJNI.SsmGetCurSens(ch);
  }

  public static int SsmGetResult(String buf, String index, String score, int ch) {
    return shctiJNI.SsmGetResult(buf, index, score, ch);
  }

  public static int SsmGetNResult(int id, String buf, String index, String score, int ch) {
    return shctiJNI.SsmGetNResult(id, buf, index, score, ch);
  }

  public static void SsmSetSil(int nValue) {
    shctiJNI.SsmSetSil(nValue);
  }

  public static void SsmSetRecoSound(int nBeginLen, int nEndLen, int nSoundLen) {
    shctiJNI.SsmSetRecoSound(nBeginLen, nEndLen, nSoundLen);
  }

  public static void SsmSetRecoTime(int nRecoTime, int nMaxWait) {
    shctiJNI.SsmSetRecoTime(nRecoTime, nMaxWait);
  }

  public static int SsmSetFlag(int ch, int nType, int lValue) {
    return shctiJNI.SsmSetFlag(ch, nType, lValue);
  }

  public static int SsmGetFlag(int ch, int nType, SWIGTYPE_p_long plValue) {
    return shctiJNI.SsmGetFlag(ch, nType, SWIGTYPE_p_long.getCPtr(plValue));
  }

  public static int SsmSetOvrlEnrgLevel(int ch, int wOvrlEnrgLevel) {
    return shctiJNI.SsmSetOvrlEnrgLevel(ch, wOvrlEnrgLevel);
  }

  public static int SsmGetOvrlEnrgLevel(int ch) {
    return shctiJNI.SsmGetOvrlEnrgLevel(ch);
  }

  public static int SsmSetOvrlEnrgDtrmTime(int ch, int wMinTime, int wMaxTime) {
    return shctiJNI.SsmSetOvrlEnrgDtrmTime(ch, wMinTime, wMaxTime);
  }

  public static int SpyGetState(int nCic) {
    return shctiJNI.SpyGetState(nCic);
  }

  public static int SpyGetCallerId(int nCic, String pcCid) {
    return shctiJNI.SpyGetCallerId(nCic, pcCid);
  }

  public static int SpyGetCalleeId(int nCic, String pcCid) {
    return shctiJNI.SpyGetCalleeId(nCic, pcCid);
  }

  public static int SpyGetCallInCh(int nCic) {
    return shctiJNI.SpyGetCallInCh(nCic);
  }

  public static int SpyGetCallOutCh(int nCic) {
    return shctiJNI.SpyGetCallOutCh(nCic);
  }

  public static int SpyGetMaxCic() {
    return shctiJNI.SpyGetMaxCic();
  }

  public static int SpyStopRecToFile(int nCic) {
    return shctiJNI.SpyStopRecToFile(nCic);
  }

  public static int SpyRecToFile(int nCic, int wDirection, String pszFileName, int nCodecFormat, long dwStartPos, long dwBytes, long dwTime, int nMask) {
    return shctiJNI.SpyRecToFile(nCic, wDirection, pszFileName, nCodecFormat, dwStartPos, dwBytes, dwTime, nMask);
  }

  public static int SpyGetLinkStatus(int nSpyPcmNo, short ucFlag) {
    return shctiJNI.SpyGetLinkStatus(nSpyPcmNo, ucFlag);
  }

  public static int SsmSetTxOriginalCallerID(int ch, SWIGTYPE_p_unsigned_char pszTxCallerId) {
    return shctiJNI.SsmSetTxOriginalCallerID(ch, SWIGTYPE_p_unsigned_char.getCPtr(pszTxCallerId));
  }

  public static int SsmSetEvent(int wEvent, int nReference, int bEnable, EVENT_SET_INFO pEventSet) {
    return shctiJNI.SsmSetEvent(wEvent, nReference, bEnable, EVENT_SET_INFO.getCPtr(pEventSet), pEventSet);
  }

  public static int SsmWaitForEvent(long dwTimeOut, MESSAGE_INFO pEvent) {
    return shctiJNI.SsmWaitForEvent(dwTimeOut, MESSAGE_INFO.getCPtr(pEvent), pEvent);
  }

  public static int SsmGetEvent(MESSAGE_INFO pEvent) {
    return shctiJNI.SsmGetEvent(MESSAGE_INFO.getCPtr(pEvent), pEvent);
  }

  public static int SsmStartTimer(int wDelay, int fuEvent) {
    return shctiJNI.SsmStartTimer(wDelay, fuEvent);
  }

  public static int SsmStopTimer(int nTimer) {
    return shctiJNI.SsmStopTimer(nTimer);
  }

}
