/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.23
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_f_int_int_p_unsigned_char_unsigned_long_p_void__int {
  private long swigCPtr;

  protected SWIGTYPE_p_f_int_int_p_unsigned_char_unsigned_long_p_void__int(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_int_int_p_unsigned_char_unsigned_long_p_void__int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_int_int_p_unsigned_char_unsigned_long_p_void__int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

